server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Captura /pokedex/ e mapeia para os arquivos estáticos internos
    location /pokedex/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /pokedex/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}